default_index:
    path:   /
    defaults: {_controller: "AppBundle:Default:index"}
    methods: GET

default_login:
    path: /login
    defaults: {_controller: "AppBundle:Default:login"}
    methods: POST

default_users:
    path: /users
    defaults: {_controller: "AppBundle:Default:getUsers"}
    methods: GET