default_index:
    path:   /
    defaults: {_controller: "AppBundle:Default:index"}
    methods: GET
    
users_index:
    path: /users
    defaults: {_controller: "AppBundle:Default:getUsers"}
    methods: GET